services:

  ostock-database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev
    volumes:
      - ./.db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./.db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ostock-network

  pga-admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.edu
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./.db/servers.json:/pgadmin4/servers.json
    depends_on:
      ostock-database:
        condition: service_healthy
    networks:
      - ostock-network

  config-server:
    image: ostock/config-server:0.0.1-SNAPSHOT
    ports:
      - 8071:8071
    networks:
      - ostock-network

  eureka-server:
    image: ostock/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_URI: http://config-server:8071
      CONFIG_SERVER_PORT: 8071
    depends_on:
      ostock-database:
        condition: service_healthy
      config-server:
        condition: service_started
    networks:
      - ostock-network

  licensing-service:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_URI: http://config-server:8071
      CONFIG_SERVER_PORT: 8071
      DATABASESERVER_PORT: 5432
    depends_on:
      ostock-database:
        condition: service_healthy
      config-server:
        condition: service_started
    networks:
      - ostock-network

  organization-service:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_URI: http://config-server:8071
      CONFIG_SERVER_PORT: 8071
      DATABASESERVER_PORT: 5432
    depends_on:
      ostock-database:
        condition: service_healthy
      config-server:
        condition: service_started
    networks:
      - ostock-network

networks:
  ostock-network:
    driver: bridge