services:

  license-database:
    image: postgres:latest
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    volumes:
      - ./.db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./.db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      ostock-network:

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "15433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.edu"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./.db/servers.json:/pgadmin4/servers.json
    depends_on:
        license-database:
            condition: service_started
    networks:
      ostock-network:

  config-server:
    image: "ostock/config-server:0.0.1-SNAPSHOT"
    ports:
      - "8071:8071"
    networks:
      ostock-network:

  licensing-service:
    image: "ostock/licensing-service:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URL: "http://config-server:8071"
      CONFIGSERVER_PORT: "8071"
    depends_on:
      config-server:
        condition: service_started
    networks:
      ostock-network:

networks:
  ostock-network:
    driver: bridge