services:

  license-database:
    image: postgres:latest
    ports:
        - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    volumes:
      - ./.db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./.db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      ostock-network:

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "15433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.edu"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./.db/servers.json:/pgadmin4/servers.json
    depends_on:
        license-database:
            condition: service_started
    networks:
      ostock-network:

  eureka-server:
    image: ostock/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
    depends_on:
      license-database:
        condition: service_started
      config-server:
        condition: service_started
    restart: on-failure:5
    networks:
      ostock-network:

  eureka-server-2:
    image: ostock/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      - "SPRING_PROFILES_ACTIVE=peer1"
    depends_on:
      license-database:
        condition: service_started
      config-server:
        condition: service_started
    restart: on-failure:5
    networks:
      ostock-network:

  eureka-server-3:
    image: ostock/eureka-server:0.0.1-SNAPSHOT
    ports:
      - "8072:8072"
    environment:
      - "SPRING_PROFILES_ACTIVE=peer2"
    depends_on:
      license-database:
        condition: service_started
      config-server:
        condition: service_started
    restart: on-failure:5
    networks:
      ostock-network:

  config-server:
    image: "ostock/config-server:0.0.1-SNAPSHOT"
    ports:
      - "8091:8091"
    networks:
      ostock-network:

  licensing-service:
    image: "ostock/licensing-service:0.0.1-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URL: "http://config-server:8091"
      CONFIGSERVER_PORT: "8091"
      DATABASE_PORT: "5432"
    depends_on:
      license-database:
        condition: service_started
      config-server:
        condition: service_started
    restart: on-failure:5
    networks:
      ostock-network:

  organization-service:
    image: "ostock/organization-service:0.0.1-SNAPSHOT"
    ports:
      - "8081:8081"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8091"
      CONFIGSERVER_PORT: "8091"
      DATABASESERVER_PORT: "5432"
    depends_on:
      license-database:
        condition: service_started
      config-server:
        condition: service_started
    restart: on-failure:5
    networks:
      ostock-network:

networks:
  ostock-network:
    driver: bridge