services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    restart: always
    ports:
      - "8080:8080"
    command:
      - start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - ostock-network

  ostock-database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ostock_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./.db/init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./.db/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ostock-network

  pga-admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.edu
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./.db/servers.json:/pgadmin4/servers.json
    depends_on:
      ostock-database:
        condition: service_healthy
    networks:
      - ostock-network

  # ... rest of the services remain unchanged ...

networks:
  ostock-network:
    driver: bridge

volumes:
  keycloak_data:
  postgres_data:
  pgadmin_data: