spring:
  application:
    name: License Service
  profiles:
    active: local

management:
  endpoints:
    access:
      default: none
  endpoint:
    health:
      access: unrestricted
      show-details: always
  health:
    db:
      enabled: false
    disk-space:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: localuser
      password: localpass
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true