spring:
  application:
    name: licensing-service
  profiles:
    active: test
  config:
    import:
      - optional:configserver:http://config-server:8071

management:
  endpoints:
    web:
      exposure:
        include: health,env
  endpoint:
    health:
      show-details: always
    env:
      show-values: always
  health:
    db:
      enabled: false
    disk-space:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:db/init.sql
      data-locations: classpath:db/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true