spring:
  application:
    name: "licensing-service"
  profiles:
    active: "dev"
  cloud:
    config:
      uri: http://config-server:8071
  config:
    import: "configserver:http://config-server:8071"

management:
  endpoint:
    health:
      access: unrestricted
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html