spring:
    application:
     name: organization-service 
    profiles:
      active: dev
    cloud:
      config:
        uri: http://config-server:8071
    config:
      import: "configserver:http://config-server:8091"