# eureka-server/src/main/resources/application-peer2.yml
spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri: http://config-server:8091
  config:
    import: "optional:configserver:http://config-server:8091"