# config-server/src/main/resources/config/eureka-server-peer2.yml
server:
  port: 8072

eureka:
  instance:
    hostname: eureka-server-3
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/,http://eureka-server-2:8071/eureka/