spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - RemoveRequestHeader=Cookie,Set-Cookie
      routes:
        - id: organization-service
          uri: lb://organization-service
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<segment>.*), /${segment}
        - id: license-service
          uri: lb://license-service
          predicates:
            - Path=/license/**
          filters:
            - RewritePath=/license/(?<segment>.*), /${segment}
        - id: google
          uri: https://www.google.com
          predicates:
            - Path=/google/**
          filters:
            - SetPath=/
        - id: arizona-edu
          uri: https://www.arizona.edu
          predicates:
              - Path=/arizona/**
          filters:
              - SetPath=/

server:
  port: 8072

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
    env:
      enabled: true
      show-values: always
    info:
      enabled: true
      show-details: always
    gateway:
      enabled: true
      show-details: always

logging:
  level:
    root: DEBUG